import type { Metadata } from 'next'
import './globals.css'


export const metadata: Metadata = {
  title: 'Country info app',
  description: 'Generated by Country info app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="max-w-screen ${inter.className} overflow-x-hidden"
      >
        {children}
      </body>
    </html>
  )
}
